spring:
  datasource:
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/bbs?useSSL=false
      username: root
      password: zhao
      driver-class-name: com.mysql.jdbc.Driver
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/crms?useSSL=false
      username: root
      password: zhao
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
